[package]
name = "pepeeltoro41/dataforge"
description = "Roblox DataStore library with cross-key transactions, session-locked and lockless profiles, migrations and an immutable data model."
version = "0.2.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = [
	"**",
]
include = [
	"default.project.json",
	"wally.toml",
	"README.md",
	"LICENSE",
	"src",
	"src/**",
]

[dependencies]

[server-dependencies]

[dev-dependencies]
